name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

#      - name: Test
#        run: dotnet test --no-restore
#
#      - name: Publish Test Coverage Report to Coveralls.io
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ./coverage.info
          
      - name: Generate Nuget Packages
        run: dotnet pack --configuration Release
        
      - name: Publish Nuget Packages to Nuget.org
        run: dotnet nuget push src/**/bin/Release/*.nupkg -k ${{secrets.Nuget_API_Key}} -s https://api.nuget.org/v3/index.json --skip-duplicate

#      - name: Publish Nuget Packages to Github
#        run: |
#          dotnet nuget add source --username litenova --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/litenova/index.json"
#          dotnet nuget push src/**/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} -s "github" --skip-duplicate 
          